name: Build with Qt 6.8.2 and CMake (with Cache)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ cmake ninja-build python3-pip

    - name: Install aqtinstall
      run: pip3 install aqtinstall

    - name: Cache Qt 6.8.2
      uses: actions/cache@v3
      with:
        path: 6.8.2
        key: qt-6.8.2-ubuntu-gcc_64
        restore-keys: |
          qt-6.8.2-ubuntu-

    - name: Install Qt 6.8.2 (if not cached)
      run: |
        if [ ! -d "6.8.2" ]; then
          aqt install-qt linux desktop 6.8.2 gcc_64 -m all
        fi

    - name: Set up environment variables
      run: |
        echo "QT_DIR=$(pwd)/6.8.2/gcc_64" >> $GITHUB_ENV
        echo "$QT_DIR/bin" >> $GITHUB_PATH

    - name: Show Qt version (for debug purposes)
      run: qmake --version

    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_PREFIX_PATH="$QT_DIR"

    - name: Build project
      run: |
        cd build
        cmake --build .

    - name: Run tests (if any)
      run: |
        cd build
        ctest --output-on-failure
